services:
  app:
    build:
      context: .
      dockerfile: cpu/Dockerfile
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    ports:
      - 8591:7860
    volumes:
      - ".cache/huggingface:/root/.cache/huggingface"
    command: "python /app/src/main.py"
